openapi: 3.0.0
info:
  title: Interview Task API
  description: Sample api for the interview task
  version: 0.0.1
  contact:
    name: 'Micha≈Ç Piotrowski'
    email: 'michal.piotrowski@ingenious.build'
servers:
  - url: http://localhost:3000
paths:
  /stops:
    get:
      summary: Returns a list of stops with time and line.
      tags:
        - 'Stops'
      responses:
        '200':
          description: A JSON array of stops
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    line:
                      type: number
                      example: 100
                    stop:
                      type: string
                      example: '3 Maja'
                    order:
                      type: number
                      example: 1
                    time:
                      type: string
                      example: '14:04'